---
functional:
  - требование 1
  - требование 2
 
  Возможность авторизации через Github
  Возможность авторизации  через Discord
 без авторизации
  Ведение рейтинга игроков по неделе/месяцу/всего и отображение на главной странице. Возможность сортировки п орейтингу, количеству игр и т.д.
Возможность кастомизации при создании лобби - сложность, задача, теги и временной лимит
  Возможность выбора языка программирования в терминале баттла
  Мультиязычность задач (русский и английский)
  Уведомление о начале баттла
  Игровой процесс
есть два редактора слева - свой редактор, справа - соперника.
Каждый игрок видит код своего соперника
  Каждый игрок имеет кнопку "check" для проверки своего решения.
  возможность переподключения
  Если вдруг один из игроков вылетел из игры, второй может продолжать играть. 
  Первый в любой момент игры, пока она не закончена, может переподключиться в игру
  Соперник тоже может выйти, а может доиграть до конца
  После определения победителя должна быть возможность остаться в баттле и дописать код / ознакомиться с кодом
  Возможность просмотра повтора баттла.
  Возможность просмотра истории баттлов
  
  что рейтинг меняется у игроков после игры но после игры с ботамит не меняется
  турнир можно стартануть и сыграть
  автокомплит
non-functional:
  - требование 3
  - требование 4
  #Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
#Сайт должен быть безопасным и защищать данные пользователя
#Сайт должен быть удобным на мобильном устройстве
#Сайт должен быть протестирован на совместимость с последними версиями браузеров
#Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - требование 5
  - требование 6

мобильная версия должна быть для людей

Проект разрабатывался вокруг одной возможности
— представить двум игрокам соревноваться друг с другом в решении задач 
и видеть написание кода друг у друга.

Unit тесты только для функций со сложной логикой (бывает не часто) - РАБОТОСПОСОБНОСТЬ МОДУЛЕЙ ПО ЧАСТЯМ НЕ ИНТЕРЕСНО - РАБОТАТЬ ДОЛЖНО ВСЕ ВМЕСТЕ
Основные тесты - тесты контроллеров ТЕСТИРУЕМ ЛОГИКУ

Codebattle — игра, в которой два программиста одновременно выполняют одну задачу на разных языках программирования. Кто выполнил быстрее, тот побеждает.

Основные возможности проекта:

Решение задачи на скорость против другого игрока. Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
Можно выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
Задачи даны на двух языках — русском и английском
Другие пользователи могут следить за ходом игры
В игре есть чат, в котором общаются зарегистрированные пользователи
Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
