---
functional:
  - требование 1
  - требование 2
non-functional:
  - требование 3
  - требование 4
implicit:
  - требование 5
  - требование 6


Проект разрабатывался вокруг одной возможности
— представить двум игрокам соревноваться друг с другом в решении задач и видеть написание кода друг у друга.

У него есть и дополнительные возможности — рейтинги, игра с ботом, игра с другом по ссылке. Они создавались постепенно из идей, которые приносили пользователи. Поэтому разработка происходила без формулирования требований.
#Исходя из здравого смысла, можно сформулировать следующие требования, которые будут подходить любому приложению или проекту:

#Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
#Сайт должен быть безопасным и защищать данные пользователя
#Сайт должен быть удобным на мобильном устройстве
#Сайт должен быть протестирован на совместимость с последними версиями браузеров
#Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)


Тестирование:

Unit тесты только для функций со сложной логикой (бывает не часто) - РАБОТОСПОСОБНОСТЬ МОДУЛЕЙ ПО ЧАСТЯМ НЕ ИНТЕРЕСНО - РАБОТАТЬ ДОЛЖНО ВСЕ ВМЕСТЕ
Основные тесты - тесты контроллеров ТЕСТИРУЕМ ЛОГИКУ =)
JS часть тестируется через jest (jsdom) + интеграция с react
