---
functional:
  - Возможность авторизации через Github
  - Возможность авторизации через Discord
  - Возможность попробовать батл без авторизации
  - Ведение и отображение на главной странице рейтинга игроков за период неделя, месяц, всего
  - Возможность фильтрации рейтинга пользователей по рангу, количеству баллов (Rating), количеству игр, времени присоединения к проекту
  - Возможность настройки при создании лобби - сложность, задача, теги и временной лимит
  
  В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Возможность выбора языка программирования в терминале баттла
  - Задачи доступны на английском или русском языке
  
  - Возможность просмотра баттла зрителям в режиме online 
  Другие пользователи могут следить за ходом игры
  - Уведомление о начале баттла
  - 
  -
  -
  
  Возможность переподключения участника к баттлу
После определения победителя должна быть возможность остаться в баттле и дописать код / ознакомиться с кодом
В истории есть иконка напротив никнейма, указывающая на победителя баттла

Возможность просмотра повтора баттла
Завершенная игра доступна в записи
Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - требование 5
  - требование 6

Каждый игрок видит код своего соперника
  Каждый игрок имеет кнопку "check" для проверки своего решения.
 
  Если вдруг один из игроков вылетел из игры, второй может продолжать играть. 
  Соперник тоже может выйти, а может доиграть до конца
  После определения победителя должна быть возможность остаться в баттле и дописать код / ознакомиться с кодом
  
  
  что рейтинг меняется у игроков после игры но после игры с ботамит не меняется
  турнир можно стартануть и сыграть
  автокомплит

мобильная версия должна быть для людей
Пользователю доступна страница своего профиля
пригласить другого пользователя находящегося онлайн

Проект разрабатывался вокруг одной возможности
— представить двум игрокам соревноваться друг с другом в решении задач 
и видеть написание кода друг у друга.

Кто выполнил быстрее, тот побеждает.
