---
functional:
  - Возможность авторизации через Github
  - Возможность авторизации через Discord
  - Возможность авторизации по почте и паролю
  - Возможность попробовать батл без авторизации
  - Ведение рейтинга игроков за период неделя, месяц, всего
  - Возможность фильтрации рейтинга пользователей по рангу, количеству баллов (Rating), количеству игр, времени присоединения к проекту
  - Возможность игры с человеком или ботом
  - Возможность настройки при создании лобби - сложность, задача, теги и временной лимит
  - Возможность выбора языка программирования в терминале баттла
  - Задачи доступны на английском или русском языке
  - Возможность просмотра баттла пользователями online
  - Обязательность уведомления о начале баттла
  - Возможность переподключения участника к баттлу
  - Возможность выхода из батла до его завершения
  - Возможность проверки решения до окончания баттла
  - Возможность просмотра во время баттла игрового поля противника
  - Возможность просмотра и написания кода в батле после определения победителя
  - Возможность просмотра повтора баттла
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Невозможно напиcать или изменить код другого участника
  - Невозможно вносить изменения в предустановленную задачу баттла
  - Невозможно вносить изменения в рейтинг вручную
