---
functional:
  - Возможность авторизации через Github
  - Возможность авторизации через Discord
  - Возможность попробовать батл без авторизации
  - Ведение на главной странице рейтинга игроков за период неделя, месяц, всего
  - Возможность фильтрации рейтинга пользователей по рангу, количеству баллов (Rating), количеству игр, времени присоединения к проекту
  - Возможность играть с человеком или ботом
  - Возможность настройки при создании лобби - сложность, задача, теги и временной лимит
  - Возможность выбора языка программирования в терминале баттла
  - Задачи доступны на английском или русском языке
  - Возможность просмотра баттла пользователями online
  - Уведомление о начале баттла
  выход
  - Возможность переподключения участника к баттлу
Если вдруг один из игроков вылетел из игры, второй может продолжать играть
  проверка
 
  Кто выполнил быстрее, тот побеждает
  
  - Возможность после определения победителя остаться в батле и дописать код или ознакомиться
  - Возможность просмотра повтора баттла
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - требование 5
  - требование 6

Участник не может писать и изменять код соперника
Зрители не могут писать код и вносить изменения в код участников
Пользователи не могут вносить изменения в таблицу лидеров вручную
Участники не могут вносить изменения в предустановленную задачу баттла


Проект разрабатывался вокруг одной возможности
— представить двум игрокам соревноваться друг с другом в решении задач 
и видеть написание кода друг у друга.
